/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Zypheos (https://sketchfab.com/zypheos)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/6b6a762bd8b34b6d9d46d44129b55037
title: Low Poly Head
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Plane_0: THREE.Mesh
  }
  materials: {
    Root: THREE.MeshStandardMaterial
  }
}

export default function LowPolyHead(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/low_poly_head/scene.gltf') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} position={[0, 1.5, 0]} >
        <group position={[4.08, 1.01, 5.9]} rotation={[-0.27, 0.6, 1.93]} scale={[1, 1, 1]} />
        <mesh castShadow receiveShadow geometry={nodes.Plane_0.geometry}>
          <meshPhongMaterial />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/low_poly_head/scene.gltf')
